# Generated by Django 5.2.6 on 2025-09-17 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Должность')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ставка/час')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Категория')),
                ('contract', models.FileField(blank=True, null=True, upload_to='employees/contracts/', verbose_name='Договор')),
                ('passport', models.FileField(blank=True, null=True, upload_to='employees/passports/', verbose_name='Паспорт')),
                ('med_book', models.FileField(blank=True, null=True, upload_to='employees/med/', verbose_name='Мед. книжка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitchen_percent', models.DecimalField(decimal_places=2, default=4, max_digits=5, verbose_name='Кухня, %')),
                ('service_percent', models.DecimalField(decimal_places=2, default=6, max_digits=5, verbose_name='Сервис, %')),
            ],
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(verbose_name='Начало недели (Пн)')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='employees.employee')),
            ],
            options={
                'unique_together': {('week_start', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='TimesheetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='employees.timesheet')),
            ],
        ),
    ]
