# Generated by Django 5.2.6 on 2025-09-10 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='dishes/', verbose_name='Фото')),
                ('composition', models.TextField(blank=True, verbose_name='Описание')),
                ('serving_weight', models.PositiveIntegerField(default=0, verbose_name='Порция, г')),
            ],
        ),
        migrations.CreateModel(
            name='DishGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Группа')),
            ],
        ),
        migrations.CreateModel(
            name='ClientMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название меню')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='crm.client')),
                ('dishes', models.ManyToManyField(blank=True, to='menuapp.dish')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dishes', to='menuapp.dishgroup'),
        ),
    ]
