# Generated by Django 5.2.6 on 2025-09-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('type', models.CharField(choices=[('хоз', 'Хоз'), ('аренда', 'Аренда'), ('комм', 'Коммуналка'), ('ремонт', 'Ремонт'), ('реклама', 'Реклама'), ('обслуж', 'Обслуживание'), ('др', 'Другое')], max_length=10, verbose_name='Тип')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Комментарий')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
