# Generated by Django 5.2.6 on 2025-09-17 06:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendarapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True, verbose_name='Продукт')),
                ('sku', models.CharField(blank=True, max_length=64, verbose_name='Артикул')),
                ('unit', models.CharField(choices=[('g', 'г'), ('kg', 'кг'), ('ml', 'мл'), ('l', 'л'), ('pcs', 'шт')], default='g', max_length=8, verbose_name='Ед. изм.')),
                ('current_qty', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, verbose_name='Остаток')),
                ('cost_per_unit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, verbose_name='Себестоимость за единицу')),
                ('min_qty', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, verbose_name='Минимальный остаток')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_change', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Изменение кол-ва')),
                ('kind', models.CharField(choices=[('PURCHASE', 'Закупка'), ('ADJUSTMENT', 'Корректировка'), ('EVENT_WRITEOFF', 'Списание по мероприятию'), ('EVENT_RETURN', 'Возврат после отмены')], max_length=32, verbose_name='Тип операции')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='calendarapp.event', verbose_name='Мероприятие')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='warehouse.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Движение склада',
                'verbose_name_plural': 'Движения склада',
                'indexes': [models.Index(fields=['event', 'kind'], name='warehouse_s_event_i_c36f0b_idx')],
            },
        ),
    ]
