# Generated by Django 5.2.6 on 2025-09-10 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Товар')),
                ('unit', models.CharField(choices=[('шт', 'шт'), ('кг', 'кг'), ('г', 'г'), ('л', 'л'), ('мл', 'мл')], default='шт', max_length=5, verbose_name='Ед.изм.')),
                ('last_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Последняя цена за ед.')),
                ('stock_qty', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Остаток')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Поставщик')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='TechCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название блюда')),
                ('output_grams', models.PositiveIntegerField(default=0, verbose_name='Выход, г')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('delta', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Корректировка')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Примечание')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='warehouse.product')),
            ],
        ),
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Кол-во (минус)')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Причина')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='warehouse.product')),
            ],
        ),
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ins', to='warehouse.product')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='TechCardIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Кол-во на блюдо')),
                ('loss_percent', models.PositiveIntegerField(default=0, verbose_name='Потери, %')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.product')),
                ('techcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='warehouse.techcard')),
            ],
        ),
    ]
