# Generated by Django 5.2.6 on 2025-09-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='stockin',
            name='note',
            field=models.CharField(blank=True, max_length=200, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='note',
            field=models.CharField(blank=True, max_length=200, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='inventoryadjustment',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='inventoryadjustment',
            name='delta',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Корректировка (+/-)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('шт', 'шт'), ('кг', 'кг'), ('г', 'г'), ('л', 'л'), ('мл', 'мл')], default='шт', max_length=5, verbose_name='Ед. изм.'),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена за ед.'),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='qty',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='stockmove',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Поставщик'),
        ),
    ]
