# Generated by Django 5.2.6 on 2025-09-17 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portions', models.PositiveIntegerField(default=1, verbose_name='Кол-во порций')),
                ('price_at_time', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена на момент добавления')),
            ],
            options={
                'verbose_name': 'Блюдо в мероприятии',
                'verbose_name_plural': 'Блюда в мероприятии',
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название зала')),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name='Вместимость')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('slot', models.CharField(choices=[('am', 'День'), ('pm', 'Вечер')], max_length=2, verbose_name='Время')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название/повод')),
                ('status', models.CharField(choices=[('in_progress', 'в работе'), ('confirmed', 'подтверждено'), ('canceled', 'отменена'), ('closed', 'закрыта')], default='in_progress', max_length=20, verbose_name='Статус')),
                ('guests', models.PositiveIntegerField(default=0, verbose_name='Количество гостей')),
                ('contract', models.FileField(blank=True, upload_to='contracts/', verbose_name='Договор')),
                ('prepayment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Предоплата, ₽')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Подтверждено в')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='Отменено в')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Закрыто в')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='crm.client', verbose_name='Клиент')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
