# Generated by Django 5.2.6 on 2025-09-10 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('menuapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Зал')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('slot', models.CharField(choices=[('am', 'Первая половина дня'), ('pm', 'Вторая половина дня')], max_length=2, verbose_name='Слот')),
                ('guests', models.PositiveIntegerField(default=0, verbose_name='Количество гостей')),
                ('contract', models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='Договор')),
                ('prepayment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Предоплата')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'В работе'), ('paid', 'Оплачено'), ('canceled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='crm.client', verbose_name='Клиент')),
                ('client_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menuapp.clientmenu', verbose_name='Меню')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='calendarapp.hall', verbose_name='Зал')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('hall', 'date', 'slot'), name='unique_hall_date_slot')],
            },
        ),
    ]
