# Generated by Django 5.2.6 on 2025-09-17 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendarapp', '0001_initial'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdish',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_lines', to='menu.dish', verbose_name='Блюдо'),
        ),
        migrations.AddField(
            model_name='eventdish',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_lines', to='calendarapp.event', verbose_name='Мероприятие'),
        ),
        migrations.AddField(
            model_name='event',
            name='dishes',
            field=models.ManyToManyField(blank=True, related_name='events', through='calendarapp.EventDish', to='menu.dish', verbose_name='Блюда'),
        ),
        migrations.AddField(
            model_name='event',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calendarapp.hall', verbose_name='Зал'),
        ),
        migrations.AlterUniqueTogether(
            name='eventdish',
            unique_together={('event', 'dish')},
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('hall', 'date', 'slot'), name='unique_hall_date_slot'),
        ),
    ]
