# Generated by Django 5.2.6 on 2025-09-14 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_alter_event_status'),
        ('crm', '0001_initial'),
        ('menuapp', '0003_extraservice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='extras',
            field=models.ManyToManyField(blank=True, to='menuapp.extraservice'),
        ),
        migrations.AddField(
            model_name='event',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='crm.client'),
        ),
        migrations.AlterField(
            model_name='event',
            name='client_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menuapp.clientmenu'),
        ),
        migrations.AlterField(
            model_name='event',
            name='contract',
            field=models.FileField(blank=True, upload_to='contracts/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='guests',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calendarapp.hall'),
        ),
        migrations.AlterField(
            model_name='event',
            name='prepayment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='event',
            name='slot',
            field=models.CharField(choices=[('am', 'День'), ('pm', 'Вечер')], max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'В работе'), ('confirmed', 'Подтверждено'), ('paid', 'Оплачено'), ('canceled', 'Отменено')], default='draft', max_length=12),
        ),
    ]
