# Generated by Django 5.2.6 on 2025-09-14 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0003_event_extras_event_responsible_event_title_and_more'),
        ('crm', '0001_initial'),
        ('menuapp', '0003_extraservice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='hall',
            options={'verbose_name': 'Зал', 'verbose_name_plural': 'Залы'},
        ),
        migrations.AddField(
            model_name='hall',
            name='capacity',
            field=models.PositiveIntegerField(default=0, verbose_name='Вместимость'),
        ),
        migrations.AlterField(
            model_name='event',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='crm.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='event',
            name='client_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menuapp.clientmenu', verbose_name='Меню'),
        ),
        migrations.AlterField(
            model_name='event',
            name='contract',
            field=models.FileField(blank=True, upload_to='contracts/', verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='event',
            name='extras',
            field=models.ManyToManyField(blank=True, to='menuapp.extraservice', verbose_name='Доп. услуги'),
        ),
        migrations.AlterField(
            model_name='event',
            name='guests',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество гостей'),
        ),
        migrations.AlterField(
            model_name='event',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calendarapp.hall', verbose_name='Зал'),
        ),
        migrations.AlterField(
            model_name='event',
            name='prepayment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Предоплата, ₽'),
        ),
        migrations.AlterField(
            model_name='event',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slot',
            field=models.CharField(choices=[('am', 'День'), ('pm', 'Вечер')], max_length=2, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'В работе'), ('confirmed', 'Подтверждено'), ('paid', 'Оплачено'), ('canceled', 'Отменено')], default='draft', max_length=12, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название/повод'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название зала'),
        ),
    ]
