# Generated by Django 5.2.6 on 2025-09-17 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendarapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория услуги',
                'verbose_name_plural': 'Категории услуг',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Фото')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Базовая стоимость')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='serviceapp.servicecategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='EventServiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кол-во')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена за ед.')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_lines', to='calendarapp.event', verbose_name='Мероприятие')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_lines', to='serviceapp.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Услуга в мероприятии',
                'verbose_name_plural': 'Услуги в мероприятии',
                'unique_together': {('event', 'service')},
            },
        ),
    ]
